// Kuratiertes Pflege-/Saison-Overlay für garten-relevante Pflanzen.
// Keys = botanischer Name GENAU wie in der Quell-Liste (inkl. dortiger Tippfehler).
// Werte sind belastbare Richtwerte für mitteleuropäisches Klima — im Formular
// anpassbar. Felder: category (Pflicht) + optional sunlight, wateringIntervalDays,
// fertilizingIntervalDays, spreadM, sowingMonths, harvestMonths, bloomMonths,
// pruningMonths. Monate 1–12.
//
// Nicht erfasste Pflanzen (Wildkräuter, Zimmerpflanzen …) bleiben schlank:
// Kategorie über genusCategory bzw. Default 'sonstiges', keine Pflegewerte.

export const careOverlay = {
  // ---- Gemüse ---------------------------------------------------------------
  'Allium cepa': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 4, spreadM: 0.15, sowingMonths: [3, 4], harvestMonths: [8, 9] },
  'Allium porrum': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 4, spreadM: 0.15, sowingMonths: [3, 4], harvestMonths: [9, 10, 11] },
  'Pastinaca sativa': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.15, sowingMonths: [3, 4], harvestMonths: [10, 11] },
  'Daucus carota': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 5, spreadM: 0.1, sowingMonths: [3, 4, 5], harvestMonths: [7, 8, 9, 10] },
  'Solanum tuberosum': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 4, fertilizingIntervalDays: 21, spreadM: 0.3, sowingMonths: [4], harvestMonths: [8, 9] },
  'Lycopersicon esculentum': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 2, fertilizingIntervalDays: 14, spreadM: 0.5, sowingMonths: [3], harvestMonths: [7, 8, 9, 10] },
  'Solanum melongena': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 2, fertilizingIntervalDays: 14, spreadM: 0.5, sowingMonths: [2, 3], harvestMonths: [8, 9] },
  'Capsicum annuum': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 2, fertilizingIntervalDays: 14, spreadM: 0.4, sowingMonths: [2, 3], harvestMonths: [8, 9, 10] },
  'Cucurbita': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 3, fertilizingIntervalDays: 14, spreadM: 1.5, sowingMonths: [5], harvestMonths: [9, 10] },
  'Cucurb. pepo convar. giromont.': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 2, fertilizingIntervalDays: 14, spreadM: 1.0, sowingMonths: [5], harvestMonths: [7, 8, 9] },
  'Cucumis melo': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 3, spreadM: 1.0, sowingMonths: [4, 5], harvestMonths: [8, 9] },
  'Phaseolus vulgaris': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [5, 6], harvestMonths: [7, 8, 9] },
  'Phaseolus vulgaris var. nanus': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [5, 6], harvestMonths: [7, 8, 9] },
  'Phaseolus coccineus': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.4, sowingMonths: [5], harvestMonths: [8, 9, 10], bloomMonths: [7, 8] },
  'Pisum sativum': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.2, sowingMonths: [3, 4], harvestMonths: [6, 7] },
  'Zea mays': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.4, sowingMonths: [5], harvestMonths: [9, 10] },
  'Lactuca sativa': { category: 'gemuese', sunlight: 'halbschatten', wateringIntervalDays: 3, spreadM: 0.25, sowingMonths: [3, 4, 5, 6, 7, 8], harvestMonths: [5, 6, 7, 8, 9, 10] },
  'Lactuca sativa var. capitata': { category: 'gemuese', sunlight: 'halbschatten', wateringIntervalDays: 3, spreadM: 0.25, sowingMonths: [3, 4, 5, 6, 7], harvestMonths: [5, 6, 7, 8, 9] },
  'Lactuca sativa var. crispa': { category: 'gemuese', sunlight: 'halbschatten', wateringIntervalDays: 3, spreadM: 0.25, sowingMonths: [3, 4, 5, 6, 7, 8], harvestMonths: [5, 6, 7, 8, 9, 10] },
  'Lactuca sativa var. acephala': { category: 'gemuese', sunlight: 'halbschatten', wateringIntervalDays: 3, spreadM: 0.25, sowingMonths: [3, 4, 5, 6, 7, 8], harvestMonths: [5, 6, 7, 8, 9, 10] },
  'Cichorium endivia': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [6, 7], harvestMonths: [9, 10, 11] },
  'Valerianella locusta': { category: 'gemuese', sunlight: 'halbschatten', spreadM: 0.1, sowingMonths: [8, 9], harvestMonths: [10, 11, 12, 1, 2, 3] },
  'Beta vulgaris ssp. vulgaris var. conditiva': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.2, sowingMonths: [4, 5], harvestMonths: [9, 10] },
  'Beta vulgaris var. cicla': { category: 'gemuese', sunlight: 'halbschatten', spreadM: 0.3, sowingMonths: [4, 5], harvestMonths: [6, 7, 8, 9, 10] },
  'Brassica oleracea var. botrytis': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 3, fertilizingIntervalDays: 21, spreadM: 0.5, sowingMonths: [3, 4], harvestMonths: [7, 8, 9] },
  'Br.ol.var. capitata f. alba': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 3, fertilizingIntervalDays: 21, spreadM: 0.5, sowingMonths: [3, 4], harvestMonths: [9, 10, 11] },
  'Br.ol.var. capitata f. rubra': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 3, fertilizingIntervalDays: 21, spreadM: 0.5, sowingMonths: [3, 4], harvestMonths: [9, 10, 11] },
  'Br.ol.var. capit. var. sabauda': { category: 'gemuese', sunlight: 'sonne', wateringIntervalDays: 3, fertilizingIntervalDays: 21, spreadM: 0.5, sowingMonths: [4, 5], harvestMonths: [10, 11] },
  'Br.ol.var. gemmifera': { category: 'gemuese', sunlight: 'sonne', fertilizingIntervalDays: 21, spreadM: 0.4, sowingMonths: [4, 5], harvestMonths: [10, 11, 12] },
  'Br.ol.var. acephala f. crispa': { category: 'gemuese', sunlight: 'sonne', fertilizingIntervalDays: 21, spreadM: 0.4, sowingMonths: [5, 6], harvestMonths: [11, 12, 1] },
  'Br.ol.var. aceph. var. gongyl.': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.25, sowingMonths: [3, 4, 5], harvestMonths: [6, 7, 8] },
  'Armoracia rusticana': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.5, harvestMonths: [10, 11] },
  'Asparagus officinalis': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.4, harvestMonths: [4, 5, 6] },
  'Cynara scölymus': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.8, harvestMonths: [8, 9], bloomMonths: [8, 9] },
  'Helianthus tuberosus': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.5, harvestMonths: [10, 11, 12], bloomMonths: [9, 10] },
  'Rheum rhabarbarum': { category: 'gemuese', sunlight: 'halbschatten', spreadM: 1.0, harvestMonths: [4, 5, 6] },
  'Apium graevolens': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [3], harvestMonths: [10, 11] },
  'Cichorium intybus': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [5, 6], harvestMonths: [10, 11], bloomMonths: [7, 8, 9] },
  'Diplotaxis tenuifolia': { category: 'gemuese', sunlight: 'sonne', spreadM: 0.2, sowingMonths: [4, 5, 6, 7, 8], harvestMonths: [5, 6, 7, 8, 9, 10] },

  // ---- Kräuter --------------------------------------------------------------
  'Ocimum basilicum': { category: 'kraeuter', sunlight: 'sonne', wateringIntervalDays: 2, spreadM: 0.25, sowingMonths: [4, 5], harvestMonths: [6, 7, 8, 9] },
  'Petroselinum crispum': { category: 'kraeuter', sunlight: 'halbschatten', spreadM: 0.2, sowingMonths: [3, 4, 5], harvestMonths: [5, 6, 7, 8, 9, 10] },
  'Anethum graveolens': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.2, sowingMonths: [4, 5, 6], harvestMonths: [6, 7, 8, 9] },
  'Anthriscus cerefolium': { category: 'kraeuter', sunlight: 'halbschatten', spreadM: 0.2, sowingMonths: [3, 4, 5, 8], harvestMonths: [5, 6, 7, 9, 10] },
  'Thymus vulgaris': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.3, harvestMonths: [6, 7, 8], bloomMonths: [6, 7] },
  'Thymus citriodorus': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.3, harvestMonths: [6, 7, 8], bloomMonths: [6, 7] },
  'Rosmarinus officinale': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.5, harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], bloomMonths: [3, 4, 5] },
  'Salvia officinalis': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.5, harvestMonths: [5, 6, 7, 8, 9], bloomMonths: [5, 6] },
  'Melissa officinalis': { category: 'kraeuter', sunlight: 'halbschatten', spreadM: 0.4, harvestMonths: [6, 7, 8, 9] },
  'Mentha piperita': { category: 'kraeuter', sunlight: 'halbschatten', spreadM: 0.4, harvestMonths: [6, 7, 8, 9] },
  'Origanum vulgare': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.4, harvestMonths: [7, 8], bloomMonths: [7, 8] },
  'Origanum sp.': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.4, harvestMonths: [7, 8], bloomMonths: [7, 8] },
  'Majorana hortensis': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.25, sowingMonths: [4, 5], harvestMonths: [7, 8, 9] },
  'Borago officinalis': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.4, sowingMonths: [4, 5], bloomMonths: [6, 7, 8] },
  'Levisticum officinalis': { category: 'kraeuter', sunlight: 'halbschatten', spreadM: 0.6, harvestMonths: [5, 6, 7, 8, 9] },
  'Allium schoenoprasum': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.2, harvestMonths: [4, 5, 6, 7, 8, 9, 10], bloomMonths: [5, 6] },
  'Ruta graveolens': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7] },
  'Nepeta cataria': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7, 8] },
  'Perilla frutescens': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [4, 5], harvestMonths: [7, 8, 9] },
  'Foenicum vulgare': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.4, sowingMonths: [4, 5], harvestMonths: [9, 10], bloomMonths: [7, 8] },
  'Lepidium sativum': { category: 'kraeuter', sunlight: 'halbschatten', spreadM: 0.1, sowingMonths: [3, 4, 5, 6, 7, 8, 9], harvestMonths: [3, 4, 5, 6, 7, 8, 9, 10] },
  'Artemisia absinthium': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.6 },
  'Artemisia abrotans': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.6 },
  'Matricaria recutita': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.2, sowingMonths: [3, 4], bloomMonths: [5, 6, 7] },
  'Tanacetum parthenium': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [6, 7, 8] },
  'Valeriana officinalis': { category: 'kraeuter', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [6, 7] },
  'Hypericum perforatum': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7, 8] },
  'Laurus nobilis': { category: 'kraeuter', sunlight: 'sonne', spreadM: 1.0 },
  'Tropaeolum majus': { category: 'kraeuter', sunlight: 'sonne', spreadM: 0.6, sowingMonths: [4, 5], bloomMonths: [6, 7, 8, 9, 10] },

  // ---- Obst -----------------------------------------------------------------
  'Malus domestica': { category: 'obst', sunlight: 'sonne', spreadM: 3.0, bloomMonths: [4, 5], harvestMonths: [9, 10], pruningMonths: [1, 2, 3] },
  'Pyrus communis': { category: 'obst', sunlight: 'sonne', spreadM: 3.0, bloomMonths: [4], harvestMonths: [8, 9, 10], pruningMonths: [1, 2] },
  'Prunus domestica': { category: 'obst', sunlight: 'sonne', spreadM: 3.0, bloomMonths: [4], harvestMonths: [8, 9], pruningMonths: [6, 7] },
  'Cerasus': { category: 'obst', sunlight: 'sonne', spreadM: 3.5, bloomMonths: [4], harvestMonths: [6, 7], pruningMonths: [6, 7] },
  'Ribes rubrum': { category: 'obst', sunlight: 'halbschatten', spreadM: 1.2, bloomMonths: [4], harvestMonths: [6, 7], pruningMonths: [1, 2] },
  'Ribes nigrum': { category: 'obst', sunlight: 'halbschatten', spreadM: 1.5, bloomMonths: [4], harvestMonths: [7], pruningMonths: [1, 2] },
  'Ribes uva-crispa': { category: 'obst', sunlight: 'halbschatten', spreadM: 1.2, bloomMonths: [4], harvestMonths: [6, 7], pruningMonths: [1, 2] },
  'Rubus idaeus': { category: 'obst', sunlight: 'halbschatten', spreadM: 0.5, bloomMonths: [5, 6], harvestMonths: [7, 8, 9] },
  'Rubus fruticosus': { category: 'obst', sunlight: 'sonne', spreadM: 1.0, bloomMonths: [6, 7], harvestMonths: [8, 9] },
  'Fragraria x ananassa': { category: 'obst', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [4, 5], harvestMonths: [6, 7] },
  'Fragaria vesca': { category: 'obst', sunlight: 'halbschatten', spreadM: 0.2, bloomMonths: [4, 5, 6], harvestMonths: [6, 7, 8, 9] },
  'Vitis vinifera': { category: 'obst', sunlight: 'sonne', spreadM: 1.5, harvestMonths: [9, 10], pruningMonths: [2, 3] },
  'Ficus carica': { category: 'obst', sunlight: 'sonne', spreadM: 2.5, harvestMonths: [8, 9] },
  'Juglans regia': { category: 'baum', sunlight: 'sonne', spreadM: 6.0, harvestMonths: [9, 10] },
  'Castanea sativa': { category: 'baum', sunlight: 'sonne', spreadM: 6.0, harvestMonths: [10] },
  'Corylus avellana': { category: 'strauch', sunlight: 'halbschatten', spreadM: 3.0, harvestMonths: [9, 10] },
  'Vaccinum myrtillus': { category: 'obst', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [5], harvestMonths: [7, 8] },
  'Actinidia deliciosa': { category: 'obst', sunlight: 'sonne', spreadM: 2.0, harvestMonths: [10] },
  'Hippophae rhamnoides': { category: 'strauch', sunlight: 'sonne', spreadM: 2.0, harvestMonths: [9, 10] },
  'Olea europaea': { category: 'baum', sunlight: 'sonne', spreadM: 2.5 },
  'Punica granatum': { category: 'strauch', sunlight: 'sonne', spreadM: 1.5, bloomMonths: [6, 7] },

  // ---- Blumen ---------------------------------------------------------------
  'Tagetes patula': { category: 'blumen', sunlight: 'sonne', spreadM: 0.25, sowingMonths: [4, 5], bloomMonths: [6, 7, 8, 9, 10] },
  'Zinnia elegans': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [4, 5], bloomMonths: [7, 8, 9, 10] },
  'Cosmos bipinnatus': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, sowingMonths: [4, 5], bloomMonths: [7, 8, 9, 10] },
  'Calendula officinalis': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [4, 5], bloomMonths: [6, 7, 8, 9, 10] },
  'Helianthus annuus': { category: 'blumen', sunlight: 'sonne', spreadM: 0.5, sowingMonths: [4, 5], bloomMonths: [7, 8, 9] },
  'Dahlia': { category: 'blumen', sunlight: 'sonne', spreadM: 0.6, bloomMonths: [7, 8, 9, 10] },
  'Tulipa': { category: 'blumen', sunlight: 'sonne', spreadM: 0.15, bloomMonths: [4, 5] },
  'Narcissus pseudonarcissus': { category: 'blumen', sunlight: 'sonne', spreadM: 0.15, bloomMonths: [3, 4] },
  'Crocus spp.': { category: 'blumen', sunlight: 'sonne', spreadM: 0.1, bloomMonths: [2, 3] },
  'Galanthus nivalis': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.1, bloomMonths: [2, 3] },
  'Hyacinthus orientalis': { category: 'blumen', sunlight: 'sonne', spreadM: 0.15, bloomMonths: [3, 4] },
  'Muscari botryoides': { category: 'blumen', sunlight: 'sonne', spreadM: 0.1, bloomMonths: [3, 4] },
  'Scilla siberica': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.1, bloomMonths: [3, 4] },
  'Eranthis hyemalis': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.1, bloomMonths: [1, 2, 3] },
  'Leucojum vernum': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.1, bloomMonths: [2, 3] },
  'Aquilegia vulgaris': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.3, bloomMonths: [5, 6] },
  'Centaurea cyanus': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, sowingMonths: [3, 4], bloomMonths: [6, 7, 8] },
  'Digitalis purpurea': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.3, bloomMonths: [6, 7] },
  'Echinacea purpurea': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [7, 8, 9] },
  'Rudbeckia fulgida': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [7, 8, 9, 10] },
  'Phlox paniculata': { category: 'blumen', sunlight: 'sonne', spreadM: 0.5, bloomMonths: [7, 8, 9] },
  'Paeonia officinalis': { category: 'blumen', sunlight: 'sonne', spreadM: 0.8, bloomMonths: [5, 6] },
  'Dicentra spectabilis': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.5, bloomMonths: [4, 5, 6] },
  'Callistephus chinensis': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [4, 5], bloomMonths: [8, 9, 10] },
  'Nigella damascena': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, sowingMonths: [4], bloomMonths: [6, 7] },
  'Lathyrus odoratus': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [4], bloomMonths: [6, 7, 8] },
  'Antirrhium majus': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [3, 4], bloomMonths: [6, 7, 8, 9] },
  'Petunia x atkinsiana': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [5, 6, 7, 8, 9, 10] },
  'Pelargonium': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [5, 6, 7, 8, 9, 10] },
  'Fuchsia': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [6, 7, 8, 9, 10] },
  'Viola x wittrockiana': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.15, bloomMonths: [3, 4, 5] },
  'Viola odorata': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.15, bloomMonths: [3, 4] },
  'Primula veris': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.15, bloomMonths: [3, 4, 5] },
  'Iris germanica': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [5, 6] },
  'Lilium martagon': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.2, bloomMonths: [6, 7] },
  'Convallaria majalis': { category: 'blumen', sunlight: 'schatten', spreadM: 0.2, bloomMonths: [5] },
  'Chrysanthemum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [9, 10, 11] },
  'Malva sylvestris': { category: 'blumen', sunlight: 'sonne', spreadM: 0.5, bloomMonths: [6, 7, 8, 9] },
  'Papaver rhoeas': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [5, 6, 7] },
  'Bellis perennis': { category: 'blumen', sunlight: 'sonne', spreadM: 0.1, bloomMonths: [3, 4, 5, 6, 7, 8, 9, 10] },

  // ---- Sträucher ------------------------------------------------------------
  'Rosa': { category: 'strauch', sunlight: 'sonne', spreadM: 1.0, bloomMonths: [6, 7, 8, 9], pruningMonths: [3] },
  'Rosa rugosa': { category: 'strauch', sunlight: 'sonne', spreadM: 1.5, bloomMonths: [6, 7, 8], harvestMonths: [9, 10] },
  'Buddleja davidii': { category: 'strauch', sunlight: 'sonne', spreadM: 2.0, bloomMonths: [7, 8, 9], pruningMonths: [3] },
  'Syringa vulgaris': { category: 'strauch', sunlight: 'sonne', spreadM: 3.0, bloomMonths: [5], pruningMonths: [6] },
  'Forsythia x intermedia': { category: 'strauch', sunlight: 'sonne', spreadM: 2.0, bloomMonths: [3, 4], pruningMonths: [4] },
  'Hydrangea macrophylla': { category: 'strauch', sunlight: 'halbschatten', spreadM: 1.5, bloomMonths: [6, 7, 8, 9] },
  'Hydrangea arborescens': { category: 'strauch', sunlight: 'halbschatten', spreadM: 1.5, bloomMonths: [7, 8, 9], pruningMonths: [3] },
  'Weigela florida': { category: 'strauch', sunlight: 'sonne', spreadM: 2.0, bloomMonths: [5, 6] },
  'Philadelphus coronarius': { category: 'strauch', sunlight: 'sonne', spreadM: 2.0, bloomMonths: [6] },
  'Ligustrum vulgare': { category: 'strauch', sunlight: 'sonne', spreadM: 1.5, pruningMonths: [6, 9] },
  'Viburnum opulus': { category: 'strauch', sunlight: 'halbschatten', spreadM: 2.0, bloomMonths: [5, 6], harvestMonths: [9, 10] },
  'Pyracantha coccinea': { category: 'strauch', sunlight: 'sonne', spreadM: 1.5, bloomMonths: [5, 6] },
  'Rhododendron': { category: 'strauch', sunlight: 'halbschatten', spreadM: 1.5, bloomMonths: [4, 5, 6] },
  'Hibiscus': { category: 'strauch', sunlight: 'sonne', spreadM: 1.5, bloomMonths: [7, 8, 9] },
  'Mahonia aquifolium': { category: 'strauch', sunlight: 'halbschatten', spreadM: 1.0, bloomMonths: [3, 4] },
  'Chaenomeles japonica': { category: 'strauch', sunlight: 'sonne', spreadM: 1.5, bloomMonths: [3, 4] },
  'Potentilla fruticosa': { category: 'strauch', sunlight: 'sonne', spreadM: 1.0, bloomMonths: [6, 7, 8, 9] },
  'Nerium oleander': { category: 'strauch', sunlight: 'sonne', spreadM: 1.5, bloomMonths: [6, 7, 8, 9] },
  'Sambucus nigra': { category: 'strauch', sunlight: 'halbschatten', spreadM: 3.0, bloomMonths: [5, 6], harvestMonths: [9] },
  'Prunus spinosa': { category: 'strauch', sunlight: 'sonne', spreadM: 2.0, bloomMonths: [3, 4], harvestMonths: [10, 11] },
  'Calluna vulgaris': { category: 'strauch', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [8, 9, 10] },

  // ---- Bäume ----------------------------------------------------------------
  'Acer pseudoplatanus': { category: 'baum', spreadM: 8.0 },
  'Aesculus hippocastanum': { category: 'baum', spreadM: 8.0, bloomMonths: [5] },
  'Betula pendula': { category: 'baum', spreadM: 5.0 },
  'Fagus sylvatica': { category: 'baum', spreadM: 8.0 },
  'Quercus robur': { category: 'baum', spreadM: 10.0 },
  'Tilia cordata': { category: 'baum', spreadM: 8.0, bloomMonths: [6, 7] },
  'Sorbus aucuparia': { category: 'baum', spreadM: 4.0, bloomMonths: [5], harvestMonths: [9] },
  'Robinia pseudoacacia': { category: 'baum', spreadM: 6.0, bloomMonths: [5, 6] },
  'Laburnum anagyroides': { category: 'baum', spreadM: 3.0, bloomMonths: [5] },
  'Larix decidua': { category: 'baum', spreadM: 4.0 },
  'Picea abies': { category: 'baum', spreadM: 4.0 },
  'Pinus sylvestris': { category: 'baum', spreadM: 4.0 },
  'Magnolia x soulangeana': { category: 'strauch', sunlight: 'sonne', spreadM: 3.0, bloomMonths: [4] },
  'Crataegus laevigata': { category: 'baum', spreadM: 3.0, bloomMonths: [5] },
  'Salix caprea': { category: 'strauch', spreadM: 3.0, bloomMonths: [3, 4] },
}

/**
 * Grobe Default-Kategorie über die Gattung (erstes Wort des botanischen Namens),
 * nur für nicht im Overlay erfasste Pflanzen. Konservativ gehalten.
 */
export const genusCategory = {
  // Bäume
  acer: 'baum', quercus: 'baum', fagus: 'baum', betula: 'baum', tilia: 'baum',
  populus: 'baum', alnus: 'baum', salix: 'baum', pinus: 'baum', picea: 'baum',
  larix: 'baum', platanus: 'baum', sequoiadendron: 'baum', araucaria: 'baum',
  aesculus: 'baum', fraxinus: 'baum', carpinus: 'baum', juglans: 'baum',
  castanea: 'baum', sorbus: 'baum', robinia: 'baum', acacia: 'baum',
  // Sträucher
  cornus: 'strauch', lonicera: 'strauch', viburnum: 'strauch', cotoneaster: 'strauch',
  symphoricarpus: 'strauch', kerria: 'strauch', kolkwitzia: 'strauch', deutzia: 'strauch',
  hydrangea: 'strauch', rhododendron: 'strauch', camellia: 'strauch', erica: 'strauch',
  juniperus: 'strauch', callicarpa: 'strauch', daphne: 'strauch', ligustrum: 'strauch',
  mahonia: 'strauch', forsythia: 'strauch', weigela: 'strauch', buddleja: 'strauch',
  syringa: 'strauch', philadelphus: 'strauch', pyracantha: 'strauch', ribes: 'strauch',
  rubus: 'strauch', rosa: 'strauch', wisteria: 'strauch', bougainvillea: 'strauch',
}
