// Zierpflanzen-Ausbau: hebt garten-relevante Einträge, die bisher als
// 'sonstiges' ohne Daten lagen, zu echten Blumen/Sträuchern mit Blütezeit +
// Pflege. Keys = botanischer Name GENAU wie im Katalog (siehe garten-de.json).
// Wird in build-catalog.mjs zusätzlich zum care-overlay eingefaltet.
// Werte = Richtwerte (mitteleuropäisch), Blütemonate füttern den Blühkalender.

export const ornamentalOverlay = {
  // ---- Stauden / Beetblumen ------------------------------------------------
  'Bergenia cordifolia': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [4, 5] },
  'Aubrieta deltoidea': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [4, 5] },
  'Lythrum salicaria': { category: 'blumen', sunlight: 'sonne', spreadM: 0.5, bloomMonths: [7, 8, 9] },
  'Anemone nemorosa': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.2, bloomMonths: [3, 4] },
  'Anemone hepatica': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.15, bloomMonths: [3, 4] },
  'Anemone hupehensis': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [8, 9, 10] },
  'Anemone coronaria': { category: 'blumen', sunlight: 'sonne', spreadM: 0.15, bloomMonths: [4, 5] },
  'Helleborus niger': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.3, bloomMonths: [12, 1, 2] },
  'Helleborus foetidus': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [2, 3, 4] },
  'Echinops ritro': { category: 'blumen', sunlight: 'sonne', spreadM: 0.5, bloomMonths: [7, 8] },
  'Sedum telephium': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [8, 9] },
  'Sedum album': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [6, 7] },
  'Sedum reflexum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [6, 7] },
  'Sempervivum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [7, 8] },
  'Centaurea montana': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [5, 6, 7] },
  'Anthemis tinctoria': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7, 8] },
  'Alchemilla mollis': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [6, 7] },
  'Campanula glomerata': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [6, 7] },
  'Campanula rotundifolia': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [6, 7, 8] },
  'Campanula trachelium': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.3, bloomMonths: [7, 8] },
  'Hosta': { category: 'blumen', sunlight: 'schatten', spreadM: 0.6, bloomMonths: [7, 8] },
  'Vinca minor': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [3, 4, 5] },
  'Polemonium caeruleum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [6, 7] },
  'Dianthus barbartus': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, sowingMonths: [5, 6], bloomMonths: [6, 7] },
  'Dianthus carthusianorum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [6, 7, 8] },
  'Dianthus caryophyllus': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [6, 7, 8] },
  'Filipendula ulmaria': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.5, bloomMonths: [6, 7, 8] },
  'Malva alcea': { category: 'blumen', sunlight: 'sonne', spreadM: 0.5, bloomMonths: [6, 7, 8, 9] },
  'Leucanthemum vulgare': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [5, 6, 7] },
  'Echium vulgare': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [6, 7, 8] },
  'Buphthalmum salicifolium': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [6, 7, 8] },
  'Astrantia major': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.3, bloomMonths: [6, 7, 8] },
  'Geranium pratense': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7] },
  'Geranium sylvaticum': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [5, 6] },
  'Geranium phaeum': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [5, 6] },
  'Lychnis flos-cuculi': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [5, 6] },
  'Silene dioica': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.3, bloomMonths: [5, 6, 7] },
  'Lychnis / Silene coronaria': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [6, 7, 8] },
  'Lupinus angustifolius': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7] },
  'Melittis melissophyllum': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.3, bloomMonths: [5, 6] },
  'Agastache rugosa': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [7, 8, 9] },
  'Caltha palustris': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [3, 4, 5] },
  'Saponaria officinalis': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7, 8] },
  'Solidago canadensis': { category: 'blumen', sunlight: 'sonne', spreadM: 0.5, bloomMonths: [8, 9, 10] },
  'Achillea filipendulina': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7, 8] },
  'Achillea millefolium': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [6, 7, 8, 9] },
  'Anaphalis margaritacea': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [7, 8, 9] },
  'Oenothera biennis': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7, 8, 9] },
  'Hesperis matronalis': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [5, 6] },
  'Helianthemum nummularium': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [5, 6, 7] },
  'Iris sibirica': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [5, 6] },
  'Iris pseudacorus': { category: 'blumen', sunlight: 'sonne', spreadM: 0.5, bloomMonths: [5, 6] },
  'Nymphaea': { category: 'blumen', sunlight: 'sonne', spreadM: 0.8, bloomMonths: [6, 7, 8, 9] },
  'Nuphar lutea': { category: 'blumen', sunlight: 'sonne', spreadM: 0.8, bloomMonths: [6, 7, 8] },
  'Primula vulgaris': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.15, bloomMonths: [3, 4] },
  'Primula elatior': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.15, bloomMonths: [3, 4, 5] },
  'Ranunculus asiaticus': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [4, 5] },
  'Delphinum cultorum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7] },
  'Iberis sempervirens': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [4, 5] },
  'Chionodoxa luciliae': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.1, bloomMonths: [3, 4] },
  'Scilla bifolia': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.1, bloomMonths: [3, 4] },
  'Allium giganteum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [5, 6] },
  'Colchium autumnale': { category: 'blumen', sunlight: 'sonne', spreadM: 0.15, bloomMonths: [9, 10] },
  'Rosea alcea': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [7, 8] },
  'Corydalis cava': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.15, bloomMonths: [3, 4] },
  'Pulmonaria obscura': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.3, bloomMonths: [3, 4] },
  'Myosotis': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.15, bloomMonths: [4, 5] },
  'Myosotis palustris': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.2, bloomMonths: [5, 6] },
  'Viola tricolor': { category: 'blumen', sunlight: 'sonne', spreadM: 0.15, bloomMonths: [4, 5, 6, 7, 8] },

  // ---- Sommerblumen / einjährig --------------------------------------------
  'Dimorphoteca sinuata': { category: 'blumen', sunlight: 'sonne', spreadM: 0.25, sowingMonths: [4, 5], bloomMonths: [6, 7, 8, 9] },
  'Ageratum houstonianum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, sowingMonths: [3, 4], bloomMonths: [6, 7, 8, 9, 10] },
  'Celosia argentea': { category: 'blumen', sunlight: 'sonne', spreadM: 0.25, sowingMonths: [4], bloomMonths: [7, 8, 9] },
  'Limonium sinuatum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.25, sowingMonths: [4], bloomMonths: [7, 8, 9] },
  'Helichrysum bracteatum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [4], bloomMonths: [7, 8, 9] },
  'Thunbergia alata': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [4], bloomMonths: [6, 7, 8, 9] },
  'Ipomoea purpurea': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, sowingMonths: [4, 5], bloomMonths: [7, 8, 9] },
  'Heliotropium arborescens': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [6, 7, 8, 9] },
  'Verbena': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [6, 7, 8, 9, 10] },
  'Lunaria annua': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.3, bloomMonths: [4, 5] },
  'Lunaria rediviva': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [4, 5] },
  'Senecio cineraria': { category: 'blumen', sunlight: 'sonne', spreadM: 0.3, bloomMonths: [7, 8] },
  'Physalis alkekengi': { category: 'blumen', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [7], harvestMonths: [9, 10] },
  'Calceolaria hybrida': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.2, bloomMonths: [4, 5, 6] },

  // ---- Zwiebel-/Knollen + Zimmerblüher (blühen, oft drinnen) ----------------
  'Cyclamen persicum': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.2, bloomMonths: [11, 12, 1, 2, 3] },
  'Hippeastrum': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [12, 1, 2, 3] },
  'Zantedescia aethiopica': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.3, bloomMonths: [5, 6, 7] },
  'Gerbera jamesonii': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [5, 6, 7, 8, 9] },
  'Strelitzia reginae': { category: 'blumen', sunlight: 'sonne', spreadM: 0.5, bloomMonths: [1, 2, 3, 11, 12] },
  'Euphorbia pulcherrima': { category: 'blumen', sunlight: 'halbschatten', spreadM: 0.4, bloomMonths: [12, 1] },
  'Kalanchoe blossfeldiana': { category: 'blumen', sunlight: 'sonne', spreadM: 0.2, bloomMonths: [1, 2, 3, 4] },
  'Freesia': { category: 'blumen', sunlight: 'sonne', spreadM: 0.15, bloomMonths: [5, 6] },

  // ---- Zier-/Kletter-Sträucher ---------------------------------------------
  'Passiflora caerulea': { category: 'strauch', sunlight: 'sonne', spreadM: 1.5, bloomMonths: [6, 7, 8, 9] },
  'Clematis vitalba': { category: 'strauch', sunlight: 'sonne', spreadM: 2.0, bloomMonths: [7, 8] },
  'Hedera helix': { category: 'strauch', sunlight: 'schatten', spreadM: 1.0, bloomMonths: [9, 10] },
  'Humulus lupulus': { category: 'strauch', sunlight: 'sonne', spreadM: 1.0, bloomMonths: [7, 8] },
  'Fallopia aubertii': { category: 'strauch', sunlight: 'sonne', spreadM: 2.0, bloomMonths: [7, 8, 9] },
  'Eyonymus europaeus': { category: 'strauch', sunlight: 'halbschatten', spreadM: 2.0, bloomMonths: [5, 6], harvestMonths: [9, 10] },
  'Malus purpurea': { category: 'strauch', sunlight: 'sonne', spreadM: 3.0, bloomMonths: [4, 5] },
  'Lavendula officinalis / angustifolia': { category: 'strauch', sunlight: 'sonne', spreadM: 0.5, bloomMonths: [6, 7, 8] },
  'Lavendula sp.': { category: 'strauch', sunlight: 'sonne', spreadM: 0.5, bloomMonths: [6, 7, 8] },
  'Lavandula multifida': { category: 'strauch', sunlight: 'sonne', spreadM: 0.4, bloomMonths: [6, 7, 8] },
}
